config/routes.rb
Microgoals::Application.routes.draw do
  resources :goals
end

app/models/form/edit_goal.rb
require 'active_model'

module Form
  class EditGoal < ::Form::Goal

    attr_reader :existing

    validates_presence_of :target

    def to_key; [existing.id] end
    def persisted?; true end
    def to_param; to_key[0] end

    def initialize(existing, data = {})
      @existing = existing

      ATTRIBUTES.each do |attr|
        self.send("#{attr}=", data.fetch(attr, existing.attributes[attr.to_s]))
      end
    end

    def save
      return false unless valid?

      existing.update_attributes!(target: target)

      true
    end
  end
end

app/models/form/goal.rb
require 'active_model'

module Form
  class Goal
    include ActiveModel::Validations
    extend ActiveModel::Naming

    ATTRIBUTES = [
      :activity,
      :target
    ]
    attr_accessor *ATTRIBUTES

    def self.name
      "Goal"
    end
  end
end

app/models/form/new_goal.rb
require 'active_model'

module Form
  class NewGoal < ::Form::Goal
    validates_presence_of :activity, :target

    def to_key; nil end
    def persisted?; false end

    def initialize(data = {})
      ATTRIBUTES.each do |attr|
        self.send("#{attr}=", data[attr])
      end
    end

    def save
      return false unless valid?

      ::Goal.create!(
        activity: activity,
        target: target
      )

      true
    end
  end
end

app/models/form/view_goal.rb
module Form
  class ViewGoal
    def self.wrap
      tenarms_map = {}
      lambda do |dao|
        x = tenarms_map[dao.tenarms_id] ||= Tenarms.new(dao.tenarms_id)
        new(dao, tenarms_data: x)
      end
    end

    def initialize(dao, tenarms_data: nil)
      @dao = dao
      @tenarms_data = tenarms_data
    end

    def activity; dao.activity end
    def target; dao.target end
    def current; tenarms_data.max_lift(dao.activity); end
    def id; dao.id end

    protected

    attr_reader :dao, :tenarms_data
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  def tenarms_id
    "T5JK51"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def sketch
    tenarms = Tenarms.new(params[:id])
    @squat_max = tenarms.max_lift("FrontSquat")
    render text: "YOUR SQUAT MAX IS: #{@squat_max.inspect}"
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all.map(&Form::ViewGoal.wrap)
  end

  def new
    @goal = Form::NewGoal.new
  end

  def create
    @goal = Form::NewGoal.new(params.require(:goal))

    if @goal.save
      redirect_to goals_path
    else
      render action: 'new'
    end
  end

  def edit
    @goal = Form::EditGoal.new(Goal.find(params.require(:id)))
  end

  def update
    @goal = Form::EditGoal.new(
      Goal.find(params.require(:id)),
      params.require(:goal)
    )

    if @goal.save
      redirect_to goals_path
    else
      render action: 'edit'
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy

    redirect_to goals_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formatting_helper.rb
module FormattingHelper
  def format_resistance(r)
    return "" unless r
    raise "Unknown type: #{r.inspect}" unless r['type'] == 'Kilos'

    "#{r['value']}kg"
  end
end

app/views/goals/edit.html.erb
<h1>Update Goal</h1>

<%= simple_form_for(@goal) do |f| %>
  <%= f.input :target %>
  <%= f.button :submit %>
<% end %>

app/views/goals/index.html.erb
<h1>Goals</h1>

<p>
  <%= link_to "New Goal", new_goal_path %>
</p>

<% @goals.each do |goal| %>
  <h3><%= goal.activity %></h3>
  <p>Current: <%= format_resistance goal.current %></p>
  <p>Target: <%= goal.target %></p>
  <%= link_to("Edit", edit_goal_path(goal.id)) %>
  <%= button_to("Delete", goal_path(goal.id), method: :delete) %>
<% end %>

app/views/goals/new.html.erb
<%= simple_form_for(@goal) do |f| %>
  <%= f.input :activity %>
  <%= f.input :target %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microgoals</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>